export const LOGIN_SCREEN_LOGIN = "LOGIN_SCREEN_LOGIN";
export const LOGIN_SCREEN_LOGIN_RESULT = "LOGIN_SCREEN_LOGIN_RESULT";
export const LOGIN_SCREEN_LOGOUT = "LOGIN_SCREEN_LOGOUT";
export const LOGIN_SCREEN_AUTO_LOGIN = "LOGIN_SCREEN_AUTO_LOGIN";